linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 4
  lll:
    line-length: 140
  misspell:
    # Correct spellings using locale preferences for US or UK.
    # Default is to use a neutral variety of English.
    # Setting locale to US will correct the British spelling of 'colour' to 'color'.
    locale: US
    ignore-words:
      - someword

linters:
  disable:
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    # structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649
    - structcheck
  enable:
    - deadcode
    - unconvert
    - megacheck
    - goconst
    - lll
    - unused
    - govet
    - misspell

run:
  timeout: 5m
  # skip-dirs:
  skip-files:
    - .*.pb.go
    - .*.xo.go
    - .*.dao.gen.go
