// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.github.heimonsy.micro.apis.user;

/**
 * Protobuf type {@code user.GetUserRequest}
 */
public final class GetUserRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:user.GetUserRequest)
    GetUserRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetUserRequest.newBuilder() to construct.
  private GetUserRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetUserRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetUserRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetUserRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            byCase_ = 1;
            by_ = input.readUInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            byCase_ = 2;
            by_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.heimonsy.micro.apis.user.UserProto.internal_static_user_GetUserRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.heimonsy.micro.apis.user.UserProto.internal_static_user_GetUserRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.heimonsy.micro.apis.user.GetUserRequest.class, com.github.heimonsy.micro.apis.user.GetUserRequest.Builder.class);
  }

  private int byCase_ = 0;
  private java.lang.Object by_;
  public enum ByCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    USER_ID(1),
    USERNAME(2),
    BY_NOT_SET(0);
    private final int value;
    private ByCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ByCase valueOf(int value) {
      return forNumber(value);
    }

    public static ByCase forNumber(int value) {
      switch (value) {
        case 1: return USER_ID;
        case 2: return USERNAME;
        case 0: return BY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ByCase
  getByCase() {
    return ByCase.forNumber(
        byCase_);
  }

  public static final int USER_ID_FIELD_NUMBER = 1;
  /**
   * <code>uint64 user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    if (byCase_ == 1) {
      return (java.lang.Long) by_;
    }
    return 0L;
  }

  public static final int USERNAME_FIELD_NUMBER = 2;
  /**
   * <code>string username = 2 [json_name = "username"];</code>
   * @return The username.
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = "";
    if (byCase_ == 2) {
      ref = by_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (byCase_ == 2) {
        by_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string username = 2 [json_name = "username"];</code>
   * @return The bytes for username.
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = "";
    if (byCase_ == 2) {
      ref = by_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (byCase_ == 2) {
        by_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (byCase_ == 1) {
      output.writeUInt64(
          1, (long)((java.lang.Long) by_));
    }
    if (byCase_ == 2) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, by_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (byCase_ == 1) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(
            1, (long)((java.lang.Long) by_));
    }
    if (byCase_ == 2) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, by_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.heimonsy.micro.apis.user.GetUserRequest)) {
      return super.equals(obj);
    }
    com.github.heimonsy.micro.apis.user.GetUserRequest other = (com.github.heimonsy.micro.apis.user.GetUserRequest) obj;

    if (!getByCase().equals(other.getByCase())) return false;
    switch (byCase_) {
      case 1:
        if (getUserId()
            != other.getUserId()) return false;
        break;
      case 2:
        if (!getUsername()
            .equals(other.getUsername())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    switch (byCase_) {
      case 1:
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
        break;
      case 2:
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUsername().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.heimonsy.micro.apis.user.GetUserRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.heimonsy.micro.apis.user.GetUserRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code user.GetUserRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:user.GetUserRequest)
      com.github.heimonsy.micro.apis.user.GetUserRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.heimonsy.micro.apis.user.UserProto.internal_static_user_GetUserRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.heimonsy.micro.apis.user.UserProto.internal_static_user_GetUserRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.heimonsy.micro.apis.user.GetUserRequest.class, com.github.heimonsy.micro.apis.user.GetUserRequest.Builder.class);
    }

    // Construct using com.github.heimonsy.micro.apis.user.GetUserRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      byCase_ = 0;
      by_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.heimonsy.micro.apis.user.UserProto.internal_static_user_GetUserRequest_descriptor;
    }

    @java.lang.Override
    public com.github.heimonsy.micro.apis.user.GetUserRequest getDefaultInstanceForType() {
      return com.github.heimonsy.micro.apis.user.GetUserRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.heimonsy.micro.apis.user.GetUserRequest build() {
      com.github.heimonsy.micro.apis.user.GetUserRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.heimonsy.micro.apis.user.GetUserRequest buildPartial() {
      com.github.heimonsy.micro.apis.user.GetUserRequest result = new com.github.heimonsy.micro.apis.user.GetUserRequest(this);
      if (byCase_ == 1) {
        result.by_ = by_;
      }
      if (byCase_ == 2) {
        result.by_ = by_;
      }
      result.byCase_ = byCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.heimonsy.micro.apis.user.GetUserRequest) {
        return mergeFrom((com.github.heimonsy.micro.apis.user.GetUserRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.heimonsy.micro.apis.user.GetUserRequest other) {
      if (other == com.github.heimonsy.micro.apis.user.GetUserRequest.getDefaultInstance()) return this;
      switch (other.getByCase()) {
        case USER_ID: {
          setUserId(other.getUserId());
          break;
        }
        case USERNAME: {
          byCase_ = 2;
          by_ = other.by_;
          onChanged();
          break;
        }
        case BY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.heimonsy.micro.apis.user.GetUserRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.heimonsy.micro.apis.user.GetUserRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int byCase_ = 0;
    private java.lang.Object by_;
    public ByCase
        getByCase() {
      return ByCase.forNumber(
          byCase_);
    }

    public Builder clearBy() {
      byCase_ = 0;
      by_ = null;
      onChanged();
      return this;
    }


    /**
     * <code>uint64 user_id = 1 [json_name = "userId"];</code>
     * @return The userId.
     */
    public long getUserId() {
      if (byCase_ == 1) {
        return (java.lang.Long) by_;
      }
      return 0L;
    }
    /**
     * <code>uint64 user_id = 1 [json_name = "userId"];</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      byCase_ = 1;
      by_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 user_id = 1 [json_name = "userId"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      if (byCase_ == 1) {
        byCase_ = 0;
        by_ = null;
        onChanged();
      }
      return this;
    }

    /**
     * <code>string username = 2 [json_name = "username"];</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = "";
      if (byCase_ == 2) {
        ref = by_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (byCase_ == 2) {
          by_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 2 [json_name = "username"];</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = "";
      if (byCase_ == 2) {
        ref = by_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (byCase_ == 2) {
          by_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 2 [json_name = "username"];</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  byCase_ = 2;
      by_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 2 [json_name = "username"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      if (byCase_ == 2) {
        byCase_ = 0;
        by_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string username = 2 [json_name = "username"];</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      byCase_ = 2;
      by_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:user.GetUserRequest)
  }

  // @@protoc_insertion_point(class_scope:user.GetUserRequest)
  private static final com.github.heimonsy.micro.apis.user.GetUserRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.heimonsy.micro.apis.user.GetUserRequest();
  }

  public static com.github.heimonsy.micro.apis.user.GetUserRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetUserRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetUserRequest>() {
    @java.lang.Override
    public GetUserRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetUserRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetUserRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetUserRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.heimonsy.micro.apis.user.GetUserRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

