// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.github.heimonsy.micro.apis.user;

public interface GetUserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.GetUserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <code>string username = 2 [json_name = "username"];</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 2 [json_name = "username"];</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string nickname = 3 [json_name = "nickname"];</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <code>string nickname = 3 [json_name = "nickname"];</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <code>.user.Gender gender = 4 [json_name = "gender"];</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.user.Gender gender = 4 [json_name = "gender"];</code>
   * @return The gender.
   */
  com.github.heimonsy.micro.apis.user.Gender getGender();
}
