// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.github.heimonsy.micro.apis.user;

public interface PushResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.PushResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.user.Event event = 1 [json_name = "event"];</code>
   * @return Whether the event field is set.
   */
  boolean hasEvent();
  /**
   * <code>.user.Event event = 1 [json_name = "event"];</code>
   * @return The event.
   */
  com.github.heimonsy.micro.apis.user.Event getEvent();
  /**
   * <code>.user.Event event = 1 [json_name = "event"];</code>
   */
  com.github.heimonsy.micro.apis.user.EventOrBuilder getEventOrBuilder();
}
