// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/user.proto

package com.github.heimonsy.micro.apis.user;

public interface RegisterResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:user.RegisterResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint64 user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  long getUserId();
}
