---
apiVersion: v1
kind: Service
metadata:
  name: micro-relation
  labels:
    micro: micro-relation
spec:
  selector:
    micro: micro-relation
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: micro-relation-headless
  labels:
    micro: micro-relation-headless
spec:
  # 用来做 grpc 客户端负载均衡
  clusterIP: None
  selector:
    micro: micro-relation
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  micro-relation
  labels:
    micro: micro-relation
spec:
  replicas: 2
  selector:
    matchLabels:
      micro: micro-relation
  template:
    metadata:
      name: micro-relation
      labels:
        micro: micro-relation
    spec:
      # imagePullSecrets:
      # - name: regcred
      # - name: regcred-vpc
      containers:
      - name: micro-relation
        image: heimonsy/micro:test-02
        args:
        - micro
        - relation
        - --listen
        - 0.0.0.0:8080
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
